name: Docker CI/CD Workflow

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository.
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Docker Buildx.
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Step 3: Log in to Docker Hub.
    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    # Step 4: Build the Docker image.
    - name: Build Docker image
      run: |
        IMAGE_TAG=arunjohnraphi/pollapp_project:${{ github.sha }}
        docker build -f Deployment/Dockerfile -t $IMAGE_TAG .
        docker images
      env:
        COMMIT_HASH: ${{ github.sha }}

