name: Docker CI/CD Workflow

on:
  push:
    branches:
    - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository.
    - name: Checkout code
      uses: actions/checkout@v3
